# Generated by Django 4.2.9 on 2026-03-11 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_selfie', models.ImageField(blank=True, null=True, upload_to='selfies/checkin/')),
                ('check_in_distance', models.FloatField(blank=True, help_text='Distance from office in meters', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
